name: Updater

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build Website
        run: |
            cd website/
            deno run -A serve.ts build
            mv dist ../server/dist

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/schlauer-hax/haxisme
          labels: |
            org.opencontainers.image.source="https://github.com/Schlauer-Hax/haxisme"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd private/ && docker compose up -d --pull always haxis.me
