name: Updater

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Install Deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.x

      - name: Build Website
        run: |
            cd website/
            deno run -A serve.ts build
            mv dist ../server/ || exit 1
            
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/schlauer-hax/haxisme
          labels: |
            org.opencontainers.image.source="https://github.com/Schlauer-Hax/haxisme"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd haxisme/ && docker compose up -d --pull always 
